spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG